"""Regenerate the ESPN lookup seeds from espn-api's constants.

ESPN's API speaks in numeric ids: a scoring category is `statId: 5`, a roster slot is
`lineupSlotId: 12`. The names live in the community espn-api package (MIT licensed,
https://github.com/cwendt94/espn-api), so they are copied here as dbt seeds rather than
hardcoded in models -- and regenerated by running this script, not by hand.

Usage:  uv run python scripts/make_espn_seeds.py
"""

from __future__ import annotations

import csv
from pathlib import Path

from espn_api.baseball.constant import (
    ACTIVITY_MAP,
    DEFAULT_POSITION_MAP,
    POSITION_MAP,
    STATS_MAP,
)

SEED_DIR = Path(__file__).resolve().parent.parent / "dbt/seeds"

# espn-api names each stat by its stored UNIT, which is not always what ESPN's UI shows.
# Where they differ, the label people recognise is recorded too, so marts and dashboards
# can use the familiar name while the pipeline keeps the honest unit.
#
# 34: ESPN displays the category as "IP" (innings pitched) but stores outs. Verified
# against landed data: matchup period 24 shows stat 34 = 144 with ERA 2.8125, and
# 2.8125 * (144/3) / 9 = exactly 15 earned runs, so 144 is outs (48.0 IP).
DISPLAY_LABELS = {34: "IP"}


def numeric_only(mapping: dict[object, object]) -> dict[int, str]:
    """Keep the id -> name direction; some espn-api maps are bidirectional."""
    return {int(key): str(value) for key, value in mapping.items() if isinstance(key, int)}


def write_seed(name: str, header: tuple[str, ...], rows: list[tuple[object, ...]]) -> None:
    path = SEED_DIR / f"{name}.csv"
    with path.open("w", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(header)
        writer.writerows(rows)
    print(f"{path.name}: {len(rows)} rows")


def main() -> None:
    SEED_DIR.mkdir(parents=True, exist_ok=True)

    stats = numeric_only(STATS_MAP)
    write_seed(
        "espn_stat_ids",
        ("stat_id", "stat_abbrev", "display_label"),
        [(key, stats[key], DISPLAY_LABELS.get(key, stats[key])) for key in sorted(stats)],
    )

    slots = numeric_only(POSITION_MAP)
    write_seed(
        "espn_lineup_slots",
        ("lineup_slot_id", "slot_abbrev"),
        [(key, slots[key]) for key in sorted(slots)],
    )

    activities = numeric_only(ACTIVITY_MAP)
    write_seed(
        "espn_activity_types",
        ("message_type_id", "activity"),
        [(key, activities[key]) for key in sorted(activities)],
    )

    positions = numeric_only(DEFAULT_POSITION_MAP)
    write_seed(
        "espn_player_positions",
        ("position_id", "position_abbrev"),
        [(key, positions[key]) for key in sorted(positions)],
    )


if __name__ == "__main__":
    main()
