"""Regenerate the ESPN lookup seeds from espn-api's constants.

ESPN's API speaks in numeric ids: a scoring category is `statId: 5`, a roster slot is
`lineupSlotId: 12`. The names live in the community espn-api package (MIT licensed,
https://github.com/cwendt94/espn-api), so they are copied here as dbt seeds rather than
hardcoded in models -- and regenerated by running this script, not by hand.

Usage:  uv run python scripts/make_espn_seeds.py
"""

from __future__ import annotations

import csv
from pathlib import Path

from espn_api.baseball.constant import (
    ACTIVITY_MAP,
    DEFAULT_POSITION_MAP,
    POSITION_MAP,
    STATS_MAP,
)

SEED_DIR = Path(__file__).resolve().parent.parent / "dbt/seeds"

# espn-api names each stat by its stored UNIT, which is not always what ESPN's UI shows.
# Where they differ, the label people recognise is recorded too, so marts and dashboards
# can use the familiar name while the pipeline keeps the honest unit.
#
# 34: ESPN displays the category as "IP" (innings pitched) but stores outs. Verified
# against landed data: matchup period 24 shows stat 34 = 144 with ERA 2.8125, and
# 2.8125 * (144/3) / 9 = exactly 15 earned runs, so 144 is outs (48.0 IP).
DISPLAY_LABELS = {34: "IP"}

# A roster slot either counts toward the day's scoring or it does not. Bench and injured
# list are the two that do not, in every ESPN league: a benched player's real-life game
# happens, it just is not credited to the fantasy team. This is a property of the slot,
# not of a particular league's settings, so it lives in the seed rather than in a model.
NON_STARTING_SLOTS = {"BE", "IL"}

# Which side of a started player's game a slot is credited with (#10): batting from hitter
# slots only, pitching from pitcher slots only. Bench and injured list credit neither.
# Every slot not named here is a hitter slot (C, 1B ... UTIL, IF).
PITCHER_SLOTS = {"P", "SP", "RP"}

# An injured-list slot is a bench slot a player cannot be started from without a roster
# move, so lineup decisions (#12) do not treat it as a candidate. Bench (BE) stays usable.
INJURED_LIST_SLOT = "IL"

# Message types espn-api's ACTIVITY_MAP does not name. 188 is the lineup move the
# unfiltered activity log also carries (#26); the name is the one the seed already holds.
EXTRA_ACTIVITIES = {188: "LINEUP MOVED"}

# Activities that rearrange a roster without moving a player between teams, so they are
# not transactions: a lineup move only changes a slot.
NON_TRANSACTION_ACTIVITIES = {"LINEUP MOVED"}

# How each transaction type moves a player (#11). One row per message type, so a type this
# table does not know has empty movement and fails the not_null test downstream instead of
# being guessed at. Empty on TRADED on purpose: a trade names two teams and moves players
# both ways, so it needs its own rule, not a place in this one.
#   movement:   add (player joins a roster) or drop (player leaves one)
#   method:     how: free_agent, waiver, or drop
#   team_field: which message field names the acting team (ADR 0004). 'to' on adds and
#               on drops 179/181; 'for' on drop 239, whose `to` is not the acting team.
TRANSACTION_RULES = {
    178: ("add", "free_agent", "to"),
    180: ("add", "waiver", "to"),
    179: ("drop", "drop", "to"),
    181: ("drop", "drop", "to"),
    239: ("drop", "drop", "for"),
}
NO_RULE = ("", "", "")


def slot_role(slot_abbrev: str) -> str:
    if slot_abbrev in NON_STARTING_SLOTS:
        return "bench"
    return "pitcher" if slot_abbrev in PITCHER_SLOTS else "hitter"


def numeric_only(mapping: dict[object, object]) -> dict[int, str]:
    """Keep the id -> name direction; some espn-api maps are bidirectional."""
    return {int(key): str(value) for key, value in mapping.items() if isinstance(key, int)}


def write_seed(name: str, header: tuple[str, ...], rows: list[tuple[object, ...]]) -> None:
    path = SEED_DIR / f"{name}.csv"
    with path.open("w", newline="") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(header)
        writer.writerows(rows)
    print(f"{path.name}: {len(rows)} rows")


def main() -> None:
    SEED_DIR.mkdir(parents=True, exist_ok=True)

    stats = numeric_only(STATS_MAP)
    write_seed(
        "espn_stat_ids",
        ("stat_id", "stat_abbrev", "display_label"),
        [(key, stats[key], DISPLAY_LABELS.get(key, stats[key])) for key in sorted(stats)],
    )

    slots = numeric_only(POSITION_MAP)
    write_seed(
        "espn_lineup_slots",
        (
            "lineup_slot_id",
            "slot_abbrev",
            "is_starting_slot",
            "slot_role",
            "is_injured_list_slot",
        ),
        [
            (
                key,
                slots[key],
                slots[key] not in NON_STARTING_SLOTS,
                slot_role(slots[key]),
                slots[key] == INJURED_LIST_SLOT,
            )
            for key in sorted(slots)
        ],
    )

    activities = numeric_only(ACTIVITY_MAP) | EXTRA_ACTIVITIES
    write_seed(
        "espn_activity_types",
        (
            "message_type_id",
            "activity",
            "is_transaction",
            "movement",
            "method",
            "team_field",
        ),
        [
            (
                key,
                activities[key],
                str(activities[key] not in NON_TRANSACTION_ACTIVITIES).lower(),
                *TRANSACTION_RULES.get(key, NO_RULE),
            )
            for key in sorted(activities)
        ],
    )

    positions = numeric_only(DEFAULT_POSITION_MAP)
    write_seed(
        "espn_player_positions",
        ("position_id", "position_abbrev"),
        [(key, positions[key]) for key in sorted(positions)],
    )


if __name__ == "__main__":
    main()
